@startuml Kampus

actor Dosen as ds  
actor Mahasiswa as mhs 

package classroom{
    usecase "Menerima penjadwalan perkuliahan" as U1
    usecase "Pilih mata kuliah" as U2
    usecase "Ruang perkuliahan" as U3
    usecase "Jadwal kuliah" as U4
    usecase "Mengajar" as U5
    usecase "Tolak mengajar" as U6
    usecase "Ntahlah" as U7
}

'selesai 
mhs --> U1
U1 .> U2
U1 .> U3
mhs --> U4
ds --> U5